### ISSUE TITLE
drop meet, link to this instead 

### ISSUE THREAD

**Issue by guaka** [Trustroots/nostr-map#2]
- [x] notes.trustroots.org points to prod server
- [ ] deploy this code to server
- [ ] change menu link: `<a href="/offer/meet">meet</a>` => `<a href="https://notes.trustroots.org/#username">notes</a>`

**Comment by chmac** [comment]
trustroots.github.io/nostr-map :-)

**Comment by chmac** [comment]
We should use the format `#user=spoofy`.

**Comment by guaka** [comment]
instead of iframe:

- [x] replace "Meet" in the menu with "Notes"
- [ ] Notes will show a page with `<a href="https://chmac.github.io/nostr-map/#spoofy">` possibly `target="_blank"`

thoughts
- cleaner, clearer
- we can add other experiments as well

**Comment by guaka** [comment]
update: only change the menu item, link to https://notes.trustroots.org/
