### ISSUE TITLE
Set DNS for GH pages

### ISSUE THREAD

**Issue by zrthstr** [Trustroots/nostr-map#6]
@guaka  could you set:

A record for `notes.trustroots.org` to, each:
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
and AAAA records to, each:
```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```

**Comment by guaka** [comment]
added the A records

**Comment by zrthstr** [comment]
unfortunately GH now demands we should set up a CNAME instead, pointing notes -> trustroots.github.io.

src:
```
notes.trustroots.org is improperly configured
Your site's DNS settings are using a custom subdomain, notes.trustroots.org, that is set up as an A record. We recommend you change this to a CNAME record pointing to trustroots.github.io. For more information, see [documentation](https://docs.github.com/articles/setting-up-a-custom-domain-with-github-pages/) (InvalidARecordError).
```

Which is in contradiction with the A / AAAA record info from: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site (5)

... sorry for that.
